server:
  port: 9050
  servlet.context-path: /account

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/lovable-account-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

stripe:
  api:
    secret: sk_test_51SqDENHfRKE4RtpC8eOYy95eunQPu6DEKUTf46tEbfjOD8MuvV5q4gFSRFl2TuP9Uez2BJma9ZqGfk15v1vYvDZM00j059kArY
  webhook:
    secret: whsec_4f78fbfe8b6638d9bf2bd3108498c097ed3fb974bb9aa81732ef732e5939c07a
